import = [
    # "~/.config/alacritty/themes/themes/coolnight.toml"
    # "~/.config/alacritty/themes/themes/everforest_dark "
    "~/.config/alacritty/themes/themes/remedy_dark"
]

[env]
TERM="xterm-256color"

[window]
padding.x=0
padding.y=0
dynamic_padding=true
dimensions.columns=133
dimensions.lines=30

decorations = "Buttonless"
# decorations = "Full"

opacity=0.8
blur=true
option_as_alt="Both"


[font]
normal.family="JetbrainsMono Nerd Font"
size=19
offset.y=20
